services:
  proxy:
    image: traefik:v3.6 # Review traefik documentation https://doc.traefik.io/traefik/
    container_name: traefik
    command:
      - --api.insecure=true
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
      - --entrypoints.web.address=:80
      - --entrypoints.web.http.redirections.entrypoint.to=websecure
      - --entrypoints.websecure.address=:443
      - --entrypoints.websecure.http.tls.certresolver=letsencrypt
      - --certificatesresolvers.letsencrypt.acme.tlschallenge=true
      - --certificatesresolvers.letsencrypt.acme.email=you@example.com
      - --certificatesresolvers.letsencrypt.acme.storage=/letsencrypt/acme.json
    ports:
      - 80:80
      - 443:443
      - 8080:8080
    volumes:
      - ./letsencrypt:/letsencrypt
      - /var/run/docker.sock:/var/run/docker.sock:ro
    restart: unless-stopped
  domain:
    image: ghcr.io/linuxserver/duckdns # Review doc https://github.com/linuxserver/docker-duckdns
    container_name: duckdns
    environment:
      - TZ=America/Chicago
      - TOKEN=59dcbfa1-b250-40c4-9f12-3dd38c8dbe74 # Required
      - SUBDOMAINS=newmanson,newmantor,newmannzb,newmanrad,newmanlid # Required
      - LOG_FILE=true #optional
    volumes:
      - ./appdata/duckdns:/config
    restart: unless-stopped
  sabnzbd:
    image: ghcr.io/linuxserver/sabnzbd
    container_name: sabnzbd
    environment:
      - PUID=1000
      - PGID=1003
      - TZ=America/Chicago
    labels:
      - traefik.enable=true
      - traefik.http.services.sabnzbd.loadbalancer.server.port=8080
      - traefik.http.routers.sabnzbd.rule=Host(`newmannzb.duckdns.org`) # Replace with your domain
    volumes:
      - ./appdata/sabnzbd:/config
      - /mnt/downloads:/downloads
      - ./downloads/nzb/incomplete:/incomplete-downloads
      - ../syncs/Sync/nzb:/watch
    restart: unless-stopped
  radarr:
    image: linuxserver/radarr
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1003
      - TZ=America/Chicago
      - UMASK=022 #optional
    labels:
      - traefik.enable=true
      - traefik.http.services.radarr.loadbalancer.server.port=7878
      - traefik.http.routers.radarr.rule=Host(`newmanrad.duckdns.org`) # Replace with your domain
    volumes:
      - ./appdata/radarr:/config
      - /mnt/perceptormedia/Video/Movies:/media
      - /mnt/ratchetmedia/Movies/:/ratchetmedia
      - /mnt/downloads:/downloads
      - /mnt/downloads/torrents/complete:/torrentdownloads
    restart: unless-stopped
  sonarr:
    image: linuxserver/sonarr:develop
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1003
      - TZ=America/Chicago
      - UMASK=022 #optional
    labels:
      - traefik.enable=true
      - traefik.http.services.sonarr.loadbalancer.server.port=8989
      - traefik.http.routers.sonarr.rule=Host(`newmanson.duckdns.org`) # Replace with your domain
    volumes:
      - ./appdata/sonarr:/config
      - /mnt/perceptormedia/Video/TV/:/media
      - /mnt/ratchetmedia/TVShows/:/ratchetmedia
      - /mnt/downloads:/downloads
    restart: unless-stopped
  lidarr:
    image: linuxserver/lidarr
    container_name: lidarr
    environment:
      - PUID=1000
      - PGID=1003
      - TZ=America/Chicago
      - UMASK=022 #optional
    labels:
      - traefik.enable=true
      - traefik.http.services.lidarr.loadbalancer.server.port=8686
      - traefik.http.routers.lidarr.rule=Host(`newmanlid.duckdns.org`) # Replace with your domain
    volumes:
      - ./appdata/lidarr:/config
      - /mnt/perceptormediaexpansion/Audio/music:/media
      - /mnt/downloads:/downloads
    restart: unless-stopped
  bazarr:
    image: lscr.io/linuxserver/bazarr:latest
    container_name: bazarr
    environment:
      - PUID=1000
      - PGID=1003
      - TZ=America/Chicago
    volumes:
      - ./appdata/bazarr:/config
      - /mnt/ratchetmedia/Movies:/ratchetmediamovies
      - /mnt/ratchetmedia/TVShows:/ratchetmediatvshows
      - /mnt/perceptormedia/Video/Movies:/Movies
      - /mnt/perceptormedia/Video/TV:/TV
    ports:
      - 6767:6767
    restart: unless-stopped
  vpn:
    image: ghcr.io/bubuntux/nordlynx
    container_name: nordvpn
    cap_add:
      - NET_ADMIN # Required
    environment: # Review https://github.com/bubuntux/nordvpn#environment-variables
      - PRIVATE_KEY=***REMOVED***
      - NET_LOCAL=192.168.0.0/24
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
      - net.ipv6.conf.all.disable_ipv6=1
    restart: unless-stopped
  torrent:
    image: ghcr.io/linuxserver/qbittorrent
    # image: ghcr.io/linuxserver/qbittorrent:14.3.9
    container_name: qbittorrent
    network_mode: service:vpn
    environment:
      - PUID=1000
      - PGID=1003
      - TZ=America/Chicago
      - WEBUI_PORT=8181
    depends_on:
      - vpn
    labels:
      - traefik.enable=true
      - traefik.http.services.torrent.loadbalancer.server.port=8181
      - traefik.http.routers.torrent.rule=Host(`newmantor.duckdns.org`) # Replace with your domain
    volumes:
      - ./appdata/qbittorrent:/config
      - /mnt/downloads/torrents:/downloads
      - ../syncs/Sync/torrent:/watch
    restart: unless-stopped
  recyclarr:
    image: ghcr.io/recyclarr/recyclarr
    container_name: recyclarr
    init: true
    user: 1000:1003
    volumes:
      - ./appdata/recyclarr:/config
    environment:
      - TZ=America/Chicago
  agregarr:
    image: agregarr/agregarr:latest
    container_name: agregarr
    volumes:
      - ./appdata/agregarr:/app/config
      - /mnt/perceptormedia/placeholders/movies:/data/movies
      - /mnt/perceptormedia/placeholders/tv:/data/tv
    environment:
      - TZ=America/Chicago
    ports:
      - 7171:7171
    restart: unless-stopped
  tautulli:
    image: tautulli/tautulli
    container_name: tautulli
    restart: unless-stopped
    volumes:
      - ./appdata/tautulli:/config
    environment:
      - PUID=1000
      - PGID=1003
      - TZ=America/Chicago
    ports:
      - 8181:8181
  seerr:
    image: ghcr.io/seerr-team/seerr:latest
    init: true
    container_name: seerr
    environment:
      - LOG_LEVEL=debug
      - PUID=1000
      - PGID=1003
      - TZ=America/Chicago
      - PORT=5055 #optional
    ports:
      - 5055:5055
    volumes:
      - ./appdata/seerr:/app/config
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:5055/api/v1/status || exit 1
      start_period: 20s
      timeout: 3s
      interval: 15s
      retries: 3
    restart: unless-stopped
  cleanuparr:
    image: ghcr.io/cleanuparr/cleanuparr:latest
    container_name: cleanuparr
    restart: unless-stopped
    ports:
      - "11011:11011"
    volumes:
      - ./appdata/cleanuparr:/config
    environment:
      - PORT=11011
      - BASE_PATH=
      - PUID=1000
      - PGID=1003
      - UMASK=022
      - TZ=America/Chicago
  profilarr:
    image: santiagosayshey/profilarr:beta # Use :beta for early access to new features
    container_name: profilarr
    ports:
      - 6868:6868
    volumes:
      - ./appdata/profilarr:/config # Replace with your actual path
    environment:
      - TZ=America/Chicago # Set your timezone
    restart: unless-stopped
  maintainerr:
    image: ghcr.io/maintainerr/maintainerr:latest # or jorenn92/maintainerr:latest
    container_name: maintainerr
    user: 1000:1003
    volumes:
      - type: bind
        source: ./appdata/maintainerr
        target: /opt/data
    environment:
      - TZ=America/Chicago # Set your timezone
      #      - BASE_PATH=/maintainerr # uncomment if you're serving maintainerr from a subdirectory
      #      - UI_HOSTNAME=:: # uncomment if you want to listen on IPv6 instead (default 0.0.0.0)
      #      - UI_PORT=6247 # uncomment to change the UI port (default 6246)
      - GITHUB_TOKEN=***REMOVED*** # Optional: GitHub Personal Access Token for higher API rate limits (60/hr without, 5000/hr with token)
    ports:
      - 6246:6246
    restart: unless-stopped
  mcsmanager-web:
    image: githubyumao/mcsmanager-web:latest
    environment:
      - PUID=1000
      - PGID=1003
      - UMASK=022
      - TZ=America/Chicago
    ports:
      - "23333:23333"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./appdata/mcsmanager-web/data:/opt/mcsmanager/web/data
      - ./appdata/mcsmanager-web/web/logs:/opt/mcsmanager/web/logs

  mcsmanager-daemon:
    image: githubyumao/mcsmanager-daemon:latest
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1003
      - UMASK=022
      - TZ=America/Chicago
      - MCSM_DOCKER_WORKSPACE_PATH=./appdata/mcsmanager-daemon/daemon/data/InstanceData
    ports:
      - "24444:24444"
      - "25565:25565"
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - ./appdata/mcsmanager-daemon/daemon/data:/opt/mcsmanager/daemon/data
      - ./appdata/mcsmanager-daemon/daemon/logs:/opt/mcsmanager/daemon/logs
      - /var/run/docker.sock:/var/run/docker.sock
  tunarr:
    image: chrisbenincasa/tunarr:latest
    container_name: tunarr
    ports:
      - ${TUNARR_SERVER_PORT:-8000}:8000
    # Uncomment if using the Nvidia container
    runtime: nvidia
    environment:
      - LOG_LEVEL=${TUNARR_LOG_LEVEL:-INFO}
      # Replace this with your timezone to ensure accurate guide
      # data and scheduling.
      - TZ=America/Chicago
      # Uncomment if you'd like to adjust default config path
      # - TUNARR_DATABASE_PATH=/your/path/tunarr
      - NVIDIA_VISIBLE_DEVICES=all
    volumes:
      # Choose a path on your host to map to /config/tunarr. This ensures
      # that restarting the container will not delete your settings or DB.
      - ./appdata/tunarr:/config/tunarr
    # The host path is relative to the location of the compose file
    # This can also use an absolute path.
    #
    # Uncomment if migrating from dizquetv. Chnage the host path
    # to the location of your dizquetv "database"
    # - ./.dizquetv:/.dizquetv
    restart: unless-stopped
