version: '3'
services:
  proxy:
    image: traefik:v2.4             # Review traefik documentation https://doc.traefik.io/traefik/
    container_name: traefik
    command:
      - --api.insecure=true
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
      - --entrypoints.web.address=:80
      - --entrypoints.web.http.redirections.entrypoint.to=websecure
      - --entrypoints.websecure.address=:443
      - --entrypoints.websecure.http.tls.certresolver=letsencrypt
      - --certificatesresolvers.letsencrypt.acme.tlschallenge=true
      - --certificatesresolvers.letsencrypt.acme.email=you@example.com
      - --certificatesresolvers.letsencrypt.acme.storage=/letsencrypt/acme.json
    ports:
      - 80:80
      - 443:443
      - 8080:8080
    volumes:
      - ./letsencrypt:/letsencrypt
      - /var/run/docker.sock:/var/run/docker.sock:ro
    restart: unless-stopped
  domain:
    image: ghcr.io/linuxserver/duckdns   # Review doc https://github.com/linuxserver/docker-duckdns
    container_name: duckdns
    environment:
      - TZ=America/Chicago
      - TOKEN=59dcbfa1-b250-40c4-9f12-3dd38c8dbe74d                    # Required
      - SUBDOMAINS=newmanson,newmantor,newmannzb,newmanrad,newmanlid       # Required
      - LOG_FILE=true #optional
    volumes:
      - ./appdata/duckdns:/config
    restart: unless-stopped
  sabnzbd:
    image: ghcr.io/linuxserver/sabnzbd
    container_name: sabnzbd
    environment:
      - PUID=1000
      - PGID=1003
      - TZ=America/Chicago
    labels:
      - traefik.enable=true
      - traefik.http.services.sabnzbd.loadbalancer.server.port=8080
      - traefik.http.routers.sabnzbd.rule=Host(`newmannzb.duckdns.org`) # Replace with your domain
    volumes:
        - ./appdata/sabnzbd:/config
        - /mnt/downloads:/media/downloads
        - ../downloads/nzb/incomplete:/media/incomplete-downloads
        - ../syncs/Sync/nzb:/watch
    restart: unless-stopped
  radarr:
    image: linuxserver/radarr
    container_name: radarr
    environment:
        - PUID=1000
        - PGID=1003
        - TZ=America/Chicago
        - UMASK=022 #optional
    labels:
      - traefik.enable=true
      - traefik.http.services.radarr.loadbalancer.server.port=7878
      - traefik.http.routers.radarr.rule=Host(`newmanrad.duckdns.org`) # Replace with your domain
    volumes:
        - ./appdata/radarr:/config
        - /mnt/media/Video/Movies:/media
        - /mnt/downloads:/downloads
        - /mnt/downloads/torrents/complete:/torrentdownloads
    restart: unless-stopped
  sonarr:
    image: linuxserver/sonarr
    container_name: sonarr
    environment:
        - PUID=1000
        - PGID=1003
        - TZ=America/Chicago
        - UMASK=022 #optional
    labels:
      - traefik.enable=true
      - traefik.http.services.sonarr.loadbalancer.server.port=8989
      - traefik.http.routers.sonarr.rule=Host(`newmanson.duckdns.org`) # Replace with your domain
    volumes:
        - ./appdata/sonarr:/config
        - /mnt/media/Video/TV/:/media
        - /mnt/downloads:/media/downloads
    restart: unless-stopped
  lidarr:
    image: linuxserver/lidarr
    container_name: lidarr
    environment:
        - PUID=1000
        - PGID=1003
        - TZ=America/Chicago
        - UMASK=022 #optional
    labels:
      - traefik.enable=true
      - traefik.http.services.lidarr.loadbalancer.server.port=8686
      - traefik.http.routers.lidarr.rule=Host(`newmanlid.duckdns.org`) # Replace with your domain
    volumes:
        - ./appdata/lidarr:/config
        - /mnt/media/Audio/music:/media
        - /mnt/downloads:/media/downloads
    restart: unless-stopped
  vpn:
#    image: ghcr.io/bubuntux/nordvpn:v3.9.5-1        # Testing
#    image: ghcr.io/bubuntux/nordvpn:latest
    image: ghcr.io/bubuntux/nordvpn:basic_ports     # Testing
    container_name: nordvpn
    cap_add:
      - NET_ADMIN               # Required
    environment:                # Review https://github.com/bubuntux/nordvpn#environment-variables
      - USER=dwnewman78@gmail.com   # Required
      - "PASS=kw4DbW32wTI3"             # Required
      - CONNECT=--group p2p United_States
#      - CONNECT=p2p us
      - TECHNOLOGY=NordLynx
      - DEBUG=Trace
    ulimits:
      memlock:
        soft: -1
        hard: -1
    restart: unless-stopped
  torrent:
    image: ghcr.io/linuxserver/qbittorrent
    container_name: qbittorrent
    network_mode: service:vpn
    environment:
      - PUID=1000
      - PGID=1003
      - TZ=America/Chicago
      - WEBUI_PORT=8181
    depends_on:
      - vpn
    labels:
      - traefik.enable=true
      - traefik.http.services.torrent.loadbalancer.server.port=8181
      - traefik.http.routers.torrent.rule=Host(`newmantor.duckdns.org`) # Replace with your domain
    volumes:
      - ./appdata/qbittorrent:/config
      - /mnt/downloads/torrents:/media/downloads
      - ../syncs/Sync/torrent:/watch
    restart: unless-stopped
