#!/usr/bin/env bash
# gen-env.sh — generate the gitignored k8s/*/env.txt secret-env files from
# the repo's .env, so real values never appear in committed manifests.
#
# Usage: k8s/scripts/gen-env.sh   (run from anywhere)
set -euo pipefail

REPO=$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)
ENV_FILE=$REPO/.env

[[ -f $ENV_FILE ]] || { echo "ERROR: $ENV_FILE not found"; exit 1; }

get() { # get KEY — last assignment wins, like docker compose interpolation
    grep -E "^$1=" "$ENV_FILE" | tail -n 1 | cut -d= -f2-
}

# Docker host LAN IP — k8s workloads reach it for ollama (permanently: the
# cluster nodes have no NVIDIA GPUs). Change here if the VM's address moves.
VM_IP=192.168.0.9

for key in CLOUDFLARE_DNS_TOKEN ACME_EMAIL LINKWARDEN_DB_PASSWORD \
    LINKWARDEN_NEXTAUTH_SECRET LINKWARDEN_MEILI_MASTER_KEY OLLAMA_MODEL \
    AUTHELIA_SESSION_SECRET AUTHELIA_STORAGE_ENCRYPTION_KEY AUTHELIA_JWT_SECRET \
    NEXTDASH_WRITE_TOKEN CONVERTX_JWT_SECRET ZIPLINE_DB_PASSWORD ZIPLINE_CORE_SECRET \
    MAINTAINERR_GITHUB_TOKEN PROTONVPN_WIREGUARD_PRIVATE_KEY GLUETUN_API_KEY \
    ROMM_DB_ROOT_PASSWORD ROMM_DB_PASSWORD ROMM_AUTH_SECRET_KEY SCREENSCRAPER_USER \
    SCREENSCRAPER_PASSWORD STEAMGRIDDB_API_KEY RETROACHIEVEMENTS_API_KEY \
    COGNEE_DB_PASSWORD COGNEE_DEFAULT_USER_PASSWORD COGNEE_TOKEN_SECRET \
    COGNEE_MCP_USER COGNEE_MCP_PASSWORD CLINE_API_KEY COGNEE_LLM_API_KEY; do
    val=$(get "$key")
    [[ -n $val ]] || { echo "ERROR: $key missing from $ENV_FILE"; exit 1; }
    printf -v "$key" '%s' "$val"
done

umask 077
mkdir -p "$REPO"/k8s/{foundation,linkwarden,auth,apps,media,cognee}

cat >"$REPO/k8s/foundation/env.txt" <<EOF
# Generated by k8s/scripts/gen-env.sh — GITIGNORED, contains real secrets
CF_DNS_API_TOKEN=$CLOUDFLARE_DNS_TOKEN
ACME_EMAIL=$ACME_EMAIL
EOF

cat >"$REPO/k8s/linkwarden/env.txt" <<EOF
# Generated by k8s/scripts/gen-env.sh — GITIGNORED, contains real secrets
POSTGRES_PASSWORD=$LINKWARDEN_DB_PASSWORD
DATABASE_URL=postgresql://postgres:$LINKWARDEN_DB_PASSWORD@linkwarden-db:5432/postgres
NEXTAUTH_SECRET=$LINKWARDEN_NEXTAUTH_SECRET
NEXTAUTH_URL=https://linkwarden.thenewmans.casa/api/v1/auth
MEILI_MASTER_KEY=$LINKWARDEN_MEILI_MASTER_KEY
NEXT_PUBLIC_OLLAMA_ENDPOINT_URL=http://$VM_IP:11434
OLLAMA_MODEL=$OLLAMA_MODEL
EOF

cat >"$REPO/k8s/auth/env.txt" <<EOF
# Generated by k8s/scripts/gen-env.sh — GITIGNORED, contains real secrets
AUTHELIA_SESSION_SECRET=$AUTHELIA_SESSION_SECRET
AUTHELIA_STORAGE_ENCRYPTION_KEY=$AUTHELIA_STORAGE_ENCRYPTION_KEY
AUTHELIA_IDENTITY_VALIDATION_RESET_PASSWORD_JWT_SECRET=$AUTHELIA_JWT_SECRET
EOF

cat >"$REPO/k8s/apps/env.txt" <<EOF
# Generated by k8s/scripts/gen-env.sh — GITIGNORED, contains real secrets
NEXTDASH_WRITE_TOKEN=$NEXTDASH_WRITE_TOKEN
JWT_SECRET=$CONVERTX_JWT_SECRET
POSTGRES_PASSWORD=$ZIPLINE_DB_PASSWORD
DATABASE_URL=postgres://zipline:$ZIPLINE_DB_PASSWORD@zipline-db:5432/zipline
CORE_SECRET=$ZIPLINE_CORE_SECRET
EOF

cat >"$REPO/k8s/media/env.txt" <<EOF
# Generated by k8s/scripts/gen-env.sh — GITIGNORED, contains real secrets
GITHUB_TOKEN=$MAINTAINERR_GITHUB_TOKEN
PROTONVPN_WIREGUARD_PRIVATE_KEY=$PROTONVPN_WIREGUARD_PRIVATE_KEY
GLUETUN_API_KEY=$GLUETUN_API_KEY
MARIADB_ROOT_PASSWORD=$ROMM_DB_ROOT_PASSWORD
MARIADB_PASSWORD=$ROMM_DB_PASSWORD
DB_PASSWD=$ROMM_DB_PASSWORD
ROMM_AUTH_SECRET_KEY=$ROMM_AUTH_SECRET_KEY
SCREENSCRAPER_USER=$SCREENSCRAPER_USER
SCREENSCRAPER_PASSWORD=$SCREENSCRAPER_PASSWORD
STEAMGRIDDB_API_KEY=$STEAMGRIDDB_API_KEY
RETROACHIEVEMENTS_API_KEY=$RETROACHIEVEMENTS_API_KEY
EOF

cat >"$REPO"/k8s/cognee/env.txt <<EOF
# Generated by k8s/scripts/gen-env.sh — GITIGNORED, contains real secrets
POSTGRES_PASSWORD=$COGNEE_DB_PASSWORD
DB_PASSWORD=$COGNEE_DB_PASSWORD
DEFAULT_USER_PASSWORD=$COGNEE_DEFAULT_USER_PASSWORD
FASTAPI_USERS_RESET_PASSWORD_TOKEN_SECRET=$COGNEE_TOKEN_SECRET
FASTAPI_USERS_VERIFICATION_TOKEN_SECRET=$COGNEE_TOKEN_SECRET
LLM_API_KEY=$CLINE_API_KEY
EOF

# cognee-mcp edge auth: traefik basicAuth reads users from the `users` key of
# the Secret named by `middleware.spec.basicAuth.secret`. gen-env computes the
# apr1 hash into a GITIGNORED file; the kustomization's second secretGenerator
# turns it into Secret/cognee-mcp-auth (same bootstrap requirement as env.txt).
MCP_HASH=$(openssl passwd -apr1 "$COGNEE_MCP_PASSWORD")
printf 'users=%s:%s\n' "$COGNEE_MCP_USER" "$MCP_HASH" > "$REPO"/k8s/cognee/users.txt

chmod 600 "$REPO"/k8s/*/env.txt "$REPO"/k8s/cognee/users.txt
echo ">>> Wrote env.txt for: foundation, linkwarden, auth, apps, media, cognee (mode 600)"
