services:
  proxy:
    image: traefik:v3.6 # Review traefik documentation https://doc.traefik.io/traefik/
    container_name: traefik
    command:
      - --api.insecure=true
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
      - --providers.file=true
      - --providers.file.watch=true
      - --providers.file.filename=/etc/traefik/dynamic-vm.yml
      - --entrypoints.web.address=:80
      - --entrypoints.web.http.redirections.entrypoint.to=websecure
      - --entrypoints.websecure.address=:443
      - --entrypoints.websecure.http.tls.certresolver=letsencrypt
      - --certificatesresolvers.letsencrypt.acme.dnschallenge=true
      - --certificatesresolvers.letsencrypt.acme.dnschallenge.provider=cloudflare
      - --certificatesresolvers.letsencrypt.acme.dnschallenge.resolvers=1.1.1.1:53,8.8.8.8:53
      - --certificatesresolvers.letsencrypt.acme.email=${ACME_EMAIL:-you@example.com}
      - --certificatesresolvers.letsencrypt.acme.storage=/letsencrypt/acme.json
    environment:
      - CF_DNS_API_TOKEN=${CLOUDFLARE_DNS_TOKEN}
    ports:
      - 80:80
      - 443:443
      - 8080:8080
    volumes:
      - ../letsencrypt:/letsencrypt
      - ../traefik-dynamic-vm-services.yml:/etc/traefik/dynamic-vm.yml:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    restart: unless-stopped

  domain:
    image: favonia/cloudflare-ddns:latest # Review doc https://github.com/favonia/cloudflare-ddns
    container_name: cloudflare-ddns
    environment:
      - CLOUDFLARE_API_TOKEN=${CLOUDFLARE_DNS_TOKEN}
      - DOMAINS=thenewmans.casa,*.thenewmans.casa
      - PROXIED=false
      - IP6_PROVIDER=none
      - TZ=${TZ:-America/Chicago}
    restart: unless-stopped